locustfile = ./scenarios/http/gateway/existing_user_get_operations/scenario.py
spawn-rate = 15
run-time = 4m
headless = true
users = 200
html = ./scenarios/http/gateway/existing_user_get_operations/report.html