locustfile = ./scenarios/http/gateway/new_user_get_documents/scenario.py
spawn-rate = 15
run-time = 3m
headless = true
users = 150
html = ./scenarios/http/gateway/new_user_issue_physical_card/report.html